# Generated by Django 2.2.1 on 2019-05-17 15:53

from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, validators=[sales.models.validate_gender])),
                ('cell', models.IntegerField(unique=True)),
                ('email', models.EmailField(default='', max_length=250, null=True)),
            ],
        ),
    ]
